my_list = ["P", "y", "t", "h", "o", "n"]
print("Here is the original list:")
print(my_list)
print()
print("The result of a temporary reverse order:")
print(sorted(my_list, reverse=True))
print()
print("Here is the original list again:")
print(my_list)
print()
print("The list was changed to:")
my_list.sort(reverse=True)
print(my_list)
print()
my_list.reverse()
print("The list was changed to:")
print(my_list)

my_list = ['P', 'y', 't', 'h', 'o', 'n']
print(f"Here is the original list:\n{my_list}")
print(f"\nThe result of a temporary reverse order:\n{sorted(my_list, reverse=True)}")
print(f"\nHere is the original list again:\n{my_list}")
my_list.sort(reverse=True)
print(f"\nThe list was changed to:\n{my_list}")
my_list.reverse()
print(f"\nThe list was changed to:\n{my_list}")
